spring:
  application:
    name: Captcha
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.118.90:8848
        username: nacos
        password: fan223
  datasource:
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://124.222.118.90:3306/fan_captcha?connectTimeout=5000&socketTimeout=10000&autoReconnect=true&failOverReadOnly=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: fan223
      validation-query: SELECT 1
  redis:
    host: 124.222.118.90
    port: 6379
    password: fan223
    database: 0
logging:
  level:
    root: info
  file:
    name: all.log
