server:
  port: 8900

spring:
  application:
    name: fan-captcha
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.xxx.xxx:8848
        username: nacos
        password: xxx
  datasource:
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://124.222.xxx.xxx:3306/fan_captcha?connectTimeout=5000&socketTimeout=10000&autoReconnect=true&failOverReadOnly=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: xxx
      validation-query: SELECT 1
  redis:
    host: 124.222.xxx.xxx
    port: 6379
    password: xxx
    database: 0

logging:
  level:
    root: info
  file:
    name: all.log
